demo-app/Veterinariav01/VeterinariaV01/VeterinariaV01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VeterinariaV01.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

demo-app/Veterinariav01/VeterinariaV01/VeterinariaV01/Controllers/MascotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VeterinariaBL;
using VeterinariaEL;

namespace VeterinariaV01.Controllers
{
    public class MascotaController : Controller
    {
        private MascotaBL mascotaBL = new MascotaBL();
        private EspecieBL especieBL = new EspecieBL();

        // GET: Mascota
        public ActionResult Index()
        {
            MascotaEL mascotaEL = new MascotaEL();
            return View(mascotaBL.ListarMascotas(mascotaEL));
        }

        public ActionResult Editar(int id = 0)
        {
            MascotaEL mascotaEL = new MascotaEL();
            EspecieEL especieEL = new EspecieEL();
            mascotaEL.MascotaId = id;
            ViewBag.Especies = especieBL.ListarEspecies(especieEL);
            return View(id == 0 ? new MascotaEL() : mascotaBL.BuscarMascotasById(mascotaEL));
        }

        public ActionResult Guardar(MascotaEL mascotaEL)
        {
            var resultado = mascotaEL.MascotaId > 0 ? mascotaBL.ActualizarMascota(mascotaEL) : mascotaBL.RegistrarMascota(mascotaEL);
            if (resultado <= 0)
            {
                ViewBag.Mensaje = "Ocurrió un error";
                return View("~/Views/Shared/_Mensaje.cshtml");
            }
            return Redirect("~/mascota/index");
        }

        public ActionResult Eliminar(int id)
        {
            MascotaEL mascotaEL = new MascotaEL();
            mascotaEL.MascotaId = id;
            var resultado = mascotaBL.EliminarMascota(mascotaEL);
            if (resultado <= 0)
            {
                ViewBag.Mensaje = "Ocurrió un error";
                return View("~/Views/Shared/_Mensaje.cshtml");
            }
            return Redirect("~/mascota/index");
        }
    }
}

demo-app/Veterinariav01/VeterinariaV01/VeterinariaV01/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

demo-app/Veterinariav01/VeterinariaV01/VeterinariaV01/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

demo-app/Veterinariav01/VeterinariaV01/VeterinariaV01/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

demo-app/Veterinariav01/VeterinariaV01/VeterinariaV01/Views/Mascota/Editar.cshtml
@model MascotaEL
@{
    ViewBag.Title = "Editar";
    List<EspecieEL> especies = ViewBag.Especies;
}

<h2>Editar</h2>
<h3>@(Model.MascotaId > 0 ? Model.Nombre : "Nueva mascota")</h3>

@using (Html.BeginForm("guardar", "mascota", FormMethod.Post))
{
    @Html.HiddenFor(x => x.MascotaId)

    <label>Nombre</label><br />
    @Html.TextBoxFor(x => x.Nombre)
    <br /><br />

    <label>Edad</label><br />
    @Html.TextBoxFor(x => x.Edad)
    <br /><br />

    <label>Especie</label><br />
    <select name="EspecieId">
        @foreach (var item in especies)
        {
            <option @(item.EspecieId == Model.EspecieId ? "selected" : "") value="@item.EspecieId">
                @item.Descripcion
            </option>
        }
    </select>
    <br /><br />

    <button type="submit">Enviar</button>
}

demo-app/Veterinariav01/VeterinariaV01/VeterinariaV01/Views/Mascota/Index.cshtml
@model List<VeterinariaEL.MascotaEL>
@{
    ViewBag.Title = "Index";
}

<h2>Mascotas</h2>
Cantidad: @Model.Count()

<a href="~/mascota/editar">Registrar mascota</a>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Edad</th>
            <th>Especie</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.Nombre</td>
            <td>@item.Edad</td>
            <td>@item.EspecieEL.Descripcion</td>
            <td>
                <a title="editar" href="~/mascota/editar/@item.MascotaId">Editar</a>
                <a title="eliminar" href="~/mascota/eliminar/@item.MascotaId">Eliminar</a>
            </td>
        </tr>
        }
    </tbody>
</table>

demo-app/Veterinariav01/VeterinariaV01/VeterinariaV01/Views/Mascota/_Mensaje.cshtml
@{
    ViewBag.Title = "_Mensaje";
}

<h2>@ViewBag.Mensaje</h2>

demo-app/Veterinariav01/VeterinariaV01/VeterinariaV01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Mascotas", "Index", "Mascota")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>